version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: razorpay-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: reimbursement_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: razorpay-web
    restart: always
    ports:
      - "7002:7002"
    environment:
      NODE_ENV: production
      PORT: 7002
      DATABASE_URL: postgresql://postgres:postgres_password@db:5432/reimbursement_db?schema=public
      JWT_SECRET: supersecretproductionjwtkey123!
      COOKIE_SECRET: supersecretproductioncookiekey123!
    depends_on:
      - db

volumes:
  pgdata:
